title: "Enquête: Restitution numérique"

project:
  type: website
  output-dir: docs

website:
  title: "Enquête numérique"
  navbar:
    background: primary
    left:
      - text: "Présentation"
        file: index.qmd
      - text: "Méthodologie"
        file: partie1.qmd
      - text: "Résultats"
        file: partie2.qmd
      - text: "Discussion"
        file: partie3.qmd
      - text: "Bibliographie"
        file: annexes.qmd
  page-footer:
    center: "© Enquête numérique: Hanâa, Abdelkader, Alia"

format:
  html:
    theme:
      light: minty
      dark: cyborg
    css: styles.css
    toc: true
    number-sections: true
    smooth-scroll: true
    code-fold: false
    link-external-newwindow: true
    lightbox: true